## backpropagation 反向传播

    在Pytorch中执行反向传播非常简便，全部的操作就是loss.backward()
    在执行反向传播之前，要先将梯度清零，否则梯度会在不同的批次数据之间被累加

In [2]:
import torch
import torch.nn as nn
from Neural_Networks import Net

input = torch.randn(1, 1, 32, 32)
net = Net()
output = net(input)
print("input:\n", input)
print("output:\n", output)

# 损失函数
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()
loss = criterion(output, target)
print("loss:\n", loss)

# 反向传播
# Pytorch中执行梯度清零的代码
net.zero_grad()

print("conv1.bias.grad before backward")
print(net.conv1.bias.grad)

# Pytorch中执行反向传播的代码
loss.backward()

print("conv1.bias.grad after backward")
print(net.conv1.bias.grad)

input:
 tensor([[[[ 0.9366, -0.5252, -1.6529,  ..., -0.9564, -0.6649,  1.5528],
          [ 1.1307,  2.1657,  0.4001,  ..., -0.8488, -0.0939,  1.0208],
          [-0.6735,  1.5474, -1.7888,  ...,  0.1283,  0.5225, -0.8565],
          ...,
          [-1.3185,  1.0852,  0.6869,  ...,  2.1979,  1.6541, -1.8709],
          [ 0.7383,  0.1899,  0.7138,  ..., -0.7484,  2.3936,  0.8467],
          [-1.7614,  0.4754,  0.4819,  ..., -0.0679, -0.9611, -0.4534]]]])
output:
 tensor([[ 0.1021,  0.1454,  0.0733, -0.0405,  0.0026, -0.0070,  0.1473, -0.0045,
          0.0162, -0.1000]], grad_fn=<AddmmBackward0>)
loss:
 tensor(0.8045, grad_fn=<MseLossBackward0>)
conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([ 0.0058,  0.0026,  0.0124, -0.0028, -0.0182, -0.0034])
