## 张量的操作

    在接下来的内容中，我们将介绍几种常见的张量的操作方法

1.加法操作

    （1）方式1：result = torch.rand(m, n)
    （2）方式2：result = troch.add(m, n)
    （3）方式3：m.add_(n)
    注意：方式3的返回值为Tensor m与n的加和结果重新赋值m

In [6]:
import torch

x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)

print("{}".format('*'*25))

# Method-one
result1 = x + y
# Method-twoo
result2 = torch.add(x, y)
# Method-three
y.add_(x)

print(result1)
print(result2)
print(y)

tensor([[0.2156, 0.5215, 0.4074],
        [0.3610, 0.6432, 0.6810],
        [0.7181, 0.4257, 0.6408],
        [0.9716, 0.0120, 0.9080],
        [0.5062, 0.4452, 0.5327]])
tensor([[0.6336, 0.6906, 0.1481],
        [0.4738, 0.9313, 0.3372],
        [0.6944, 0.9710, 0.2978],
        [0.3384, 0.0227, 0.4610],
        [0.1008, 0.3512, 0.7358]])
*************************
tensor([[0.8493, 1.2122, 0.5555],
        [0.8349, 1.5746, 1.0183],
        [1.4124, 1.3967, 0.9386],
        [1.3101, 0.0347, 1.3690],
        [0.6070, 0.7965, 1.2685]])
tensor([[0.8493, 1.2122, 0.5555],
        [0.8349, 1.5746, 1.0183],
        [1.4124, 1.3967, 0.9386],
        [1.3101, 0.0347, 1.3690],
        [0.6070, 0.7965, 1.2685]])
tensor([[0.8493, 1.2122, 0.5555],
        [0.8349, 1.5746, 1.0183],
        [1.4124, 1.3967, 0.9386],
        [1.3101, 0.0347, 1.3690],
        [0.6070, 0.7965, 1.2685]])


2.索引操作

    需要注意的是：所以出来的结果与原数据共享内存，修改一个，另一个会跟着修改。
    如果不想修改，可以考虑使用copy()等方法

In [8]:
import torch
x = torch.rand(4,3)
print(x)
# 取出第二列
print(x[:, 1])

tensor([[0.2113, 0.8953, 0.3662],
        [0.6028, 0.7400, 0.1179],
        [0.1867, 0.1861, 0.0493],
        [0.6204, 0.3651, 0.7880]])
tensor([0.8953, 0.7400, 0.1861, 0.3651])


In [9]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([1.2113, 1.8953, 1.3662])
tensor([1.2113, 1.8953, 1.3662])


3.维度变换

    维度变换常见的方法有：torch.view()和torch.reshape()，
    方法一：torch.view()
    注意：torch.view()返回的新tensor与源tensor共享内存（其实是同一个tensor），更
    改其中的一个，另外一个也会跟着改变（顾名思义，view()仅仅是改变了对这个张量的观察角度。）

In [11]:
import torch

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)   # -1是指这一维的维数由其他的维度决定

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
x += 1
print(x)
print(y)

tensor([[ 1.8338,  0.6893,  0.8936,  2.4812],
        [ 0.9748,  0.3209,  0.7328,  1.1892],
        [ 1.2749, -0.3591,  2.7221,  1.0204],
        [ 1.2666,  1.5340, -0.3581,  0.6846]])
tensor([ 1.8338,  0.6893,  0.8936,  2.4812,  0.9748,  0.3209,  0.7328,  1.1892,
         1.2749, -0.3591,  2.7221,  1.0204,  1.2666,  1.5340, -0.3581,  0.6846])


    面我们说过torch.view()会改变原始张量，但是很多情况下，我们希望原始张量和变换后的
    张量互相不影响。为为了使创建的张量和原始张量不共享内存，我们需要使用第二种方法
    torch.reshape()， 同样可以改变张量的形状，但是此函数并不能保证返回的是其拷贝值，
    所以官方不推荐使用。

    推荐的方法是我们先用 clone() 创造一个张量副本然后再使用 torch.view()进行函数维度变换 。

    注：使用 clone() 还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源 
    Tensor 。 3. 取值操作 如果我们有一个元素 tensor ，我们可以使用 .item() 来获得
    这个 value，而不获得其他性质：

In [13]:
import torch 
x = torch.randn(1)
print(type(x))
print(type(x.item()))   # 注意：item（）只能访问含有一个元素的张量，如果被访问的张量有超过一个元素就会报错

<class 'torch.Tensor'>
<class 'float'>
