## 梯度

    在Pytorch中，反向传播是依靠.backward（）实现的。
    out.backward()

In [4]:
import torch
# 创建一个张量，并设置requires-grad = True用来追踪其计算历史
x = torch.ones(2, 2, requires_grad=True)
print(x)
# 对这个张量做一次运算
y = x ** 2
print(y)
# y是计算的结果，所以它有grad_fn属性
print(y.grad_fn)
# 对y进行更多的操作
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>)
tensor(3., grad_fn=<MeanBackward0>)


In [5]:
out.backward()
print(x.grad)

tensor([[3., 3.],
        [3., 3.]])


    关于自动求导的属性设置：可以通过设置 .requires_grad=True来执行自动求导，也可以通
    过迭代码块的限制来停止自动求导。

In [6]:
print(x.requires_grad)
print((x ** 2).requires_grad)

# 通过代码块终止求导
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


    可以通过 .detach()获得一个新的Tensor，拥有相同的内容但不需要自动求导

In [7]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
